### ISSUE TITLE
Suggestion for part/2x2-rok-block.md

### ISSUE THREAD

**Issue by jbbatson** [TechplexEngineer/Rokenbok-Archive#10]
**- What change should be made?**
The 2x2 blocks that came with the ROK Jr. set I have break.These need to be made out of different plastics that are not so brittle.  When these break they have shards of plastic that could injure someone. 
**- What is the source for the information?**
Out of the 18 2x2 blocks there are only11 that haven't been broken yet.  This is with us being as gentle as possible.  These break trying to assemble and take appart.
**Images and files can be attached to the issue**
![IMG_4870](https://github.com/user-attachments/assets/92095f8a-f052-4b05-9214-bff49a31498f)
![IMG_4879](https://github.com/user-attachments/assets/8344fc85-a527-450d-901b-6ed483992944)
![IMG_4878](https://github.com/user-attachments/assets/1776c18e-2412-4b4d-94a5-bb06adcaf173)
![IMG_4871](https://github.com/user-attachments/assets/61378b83-155e-4dc6-baa7-4a42cd5e401a)
![IMG_4872](https://github.com/user-attachments/assets/67800cdd-0e99-4eda-b3ab-f71c489723f9)
![IMG_4873](https://github.com/user-attachments/assets/8fd8dbee-49a2-4d65-b210-ae9231df4440)
![IMG_4875](https://github.com/user-attachments/assets/dc21a463-8281-43f3-928b-f51f9ab43591)
![IMG_4876](https://github.com/user-attachments/assets/5e107996-5147-4a51-b883-d5283e594abb)

**Please include a link to the source of any images or files**

**Comment by TechplexEngineer** [comment]
Hi @jbbatson, thanks for your detailed report. This is a fan-run site and I have no contacts at Rokenbok. You may want to share this with them, however I believe most if not all of the sets are out of production now. In my own personal collection I have seen similar breaks often caused by sun exposure.
